package com.lx.miaosha.dao;

import com.lx.miaosha.entity.ProductStockDO;

public interface ProductStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    int insert(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    int insertSelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    ProductStockDO selectByPrimaryKey(Integer id);
    ProductStockDO selectByProductId(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    int updateByPrimaryKeySelective(ProductStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated Thu Aug 15 16:48:05 CST 2019
     */
    int updateByPrimaryKey(ProductStockDO record);
}